--CREATE DATABASE JOBS_CONTROLE
--USE JOBS_CONTROLE
go
CREATE TABLE TICKET
(
	ID_JOBCONTROLE BIGINT IDENTITY(1,1) NOT NULL,
	DATA_VIGENCIA DATETIME NOT NULL,
	DATA_ENTRADA DATETIME  DEFAULT  GETDATE() NOT NULL,
	IDPROCESSO INT NOT NULL,
	QUANTIDADE INT,
	SEGMENTACAO VARCHAR(MAX) NOT NULL,
	STATUS VARCHAR(60),
	ID_USUARIO INT NOT NULL,
	IP_USUARIO VARCHAR(20) NOT NULL,
	VALOR_PROCESSO DECIMAL(18,4) NOT NULL,
	ID_VENDEDOR INT NOT NULL,
	ID_ARQUIVO INT NOT NULL,
	CONSTRAINT PK_ID_JOBCONTROLE PRIMARY KEY (ID_JOBCONTROLE)	
)

CREATE TABLE PROCESSO
(
	ID_PROCESSO INT IDENTITY(1,1)  NOT NULL,
	NOME_PRECESSO VARCHAR(20)  NOT NULL,
	CONSTRAINT PK_ID_PROCESSO PRIMARY KEY (ID_PROCESSO)
)

CREATE TABLE TICKET_LOG
(
	ID_JOBCONTROLE_LOG BIGINT IDENTITY(1,1),
	ID_JOBCONTROLE BIGINT NOT NULL,
	DATA_VIGENCIA DATETIME NOT NULL,
	DATA_AUTERACAO DATETIME NOT NULL,
	ID_PROCESSO INT NOT NULL,
	QUANTIDADE BIGINT,
	SEGMENTACAO VARCHAR(MAX) NOT NULL,

	ID_USUARIO INT NOT NULL,
	IP_USUARIO VARCHAR(20) NOT NULL,
	VALOR_PROCESSO DECIMAL(18,4)  NOT NULL,


	CONSTRAINT PK_ID_JOBCONTROLE_LOG PRIMARY KEY (ID_JOBCONTROLE_LOG)
)
use JOBS_CONTROLE

DROP TABLE TICKET
DROP TABLE PROCESSO
DROP TABLE TICKET_LOG




INSERT INTO PROCESSO(NOME_PRECESSO) VALUES ('AMOSTRA')
INSERT INTO PROCESSO(NOME_PRECESSO) VALUES ('CONTAGEM')
INSERT INTO PROCESSO(NOME_PRECESSO) VALUES ('MALING')
INSERT INTO PROCESSO(NOME_PRECESSO) VALUES ('AMOSTRA / MALING')
INSERT INTO PROCESSO(NOME_PRECESSO) VALUES ('AMOSTRA / CONTAGEM')
INSERT INTO PROCESSO(NOME_PRECESSO) VALUES ('CONTAGEM / MALING')

--------------------------------------------------------------------------------------------------------------
USE JOBS_CONTROLE



CREATE PROCEDURE PROC_INSERIR_TICKET
	@DATA_VIGENCIA DATETIME ,
	@ID_PROCESSO INT,
	@QUANTIDADE BIGINT,
	@SEGMENTACAO VARCHAR(60),
	@STATUS_PROCESSO VARCHAR(60),
	@ID_USUARIO INT ,
	@IP_USUARIO INT ,
	@VALOR_PROCESSO DECIMAL ,
	@ID_VENDEDOR INT
	
AS 
BEGIN

INSERT INTO TICKET(DATA_VIGENCIA, IDPROCESSO, QUANTIDADE, SEGMENTACAO, STATUS, ID_USUARIO, IP_USUARIO, VALOR_PROCESSO, ID_VENDEDOR )
	VALUES (
		@DATA_VIGENCIA, 
		@ID_PROCESSO, 
		@QUANTIDADE, 
		@SEGMENTACAO, 
		'PROCESSANDO',
		@ID_USUARIO,
		@IP_USUARIO,
		@VALOR_PROCESSO,
		@ID_VENDEDOR
	)
	
END 


-----------------


CREATE PROCEDURE PROC_OBTER_PROCESSOS
AS 
BEGIN
SELECT * FROM PROCESSO
END